stages: # List of stages for jobs, and their order of execution
  - develop-deploy
  - stage-deploy
  - deploy

ci-development-job:
  stage: develop-deploy
  only:
    - develop
    - ci-working
  script:
    - cp .env.branch-develop ".env.production"
    - bash scripts/build_sheepkainet.sh $CI_BUILD_REF_NAME "develop" "61080"

deploy-production-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  only:
    - stage
    - deploy
  script:
    - rm -rf ./.git
    - cp .env.branch-${CI_BUILD_REF_NAME} ".env.production"
    - docker build  --no-cache --force-rm=true --target deploy-stage -t sheepkai-menu-front:${CI_BUILD_REF_NAME} ./
    - sh /scripts/docker_login.sh
    - docker tag sheepkai-menu-front:${CI_BUILD_REF_NAME} registry.sheepkai.net:5000/sheepkainet/sheepkai-menu-front:${CI_BUILD_REF_NAME}
    - docker push registry.sheepkai.net:5000/sheepkainet/sheepkai-menu-front:${CI_BUILD_REF_NAME}
    - sh /scripts/reflesh_cpane.sh sheepkai-menu-front-${CI_BUILD_REF_NAME}
    - bash /scripts/cloudflare_cache_purge.sh
